### ISSUE TITLE
你好，问一下有数据集吗

### ISSUE THREAD

**Issue by hiahiawei** [ittqqzz/ECommerceRecommendSystem#4]

**Comment by ittqqzz** [comment]
https://github.com/ittqqzz/ECommerceRecommendSystem/tree/master/backend/recommender/DataLoader/src/main/resources

数据集来自亚马逊中文网，你可以去google上拿到对应的数据：https://blog.csdn.net/qq_27032425/article/details/78693767

**Comment by hiahiawei** [comment]
谢谢😜------------------ 原始邮件 ------------------
发件人: "tqz啊"<notifications@github.com>
发送时间: 2019年12月6日(星期五) 中午11:46
收件人: "ittqqzz/ECommerceRecommendSystem"<ECommerceRecommendSystem@noreply.github.com>;
抄送: "hiahiawei"<2392475234@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ittqqzz/ECommerceRecommendSystem] 你好，问一下有数据集吗 (#4)



https://github.com/ittqqzz/ECommerceRecommendSystem/tree/master/backend/recommender/DataLoader/src/main/resources
 
数据集来自亚马逊中文网，你可以去google上拿到对应的数据：https://blog.csdn.net/qq_27032425/article/details/78693767
 
&mdash;
