### ISSUE TITLE
redis无法连接

### ISSUE THREAD

**Issue by waterzmh** [ittqqzz/ECommerceRecommendSystem#5]
首先说明下，我将redis的配置换成自己的，可以成功运行。
如果按源码的配置参数，调用打分接口则会报出下述错误.
Request processing failed; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused (Connection refused)] with root cause
@ittqqzz 检查下redis的配置是否忘记了上传某些参数，比如端口号之类的？

**Comment by ittqqzz** [comment]
README 里面说了的，所有涉及到 IP 的地方全部要改（不改，直接用我的也行），包括 business 与 recommend 模块。因为我自己不想在本地搭建中间件，所以把中间件全部上云。
但是我把阿里云 Redis 下线了，所以你会报错！可以自己搭建Redis中间价并修改IP

**Comment by ittqqzz** [comment]
> 首先说明下，我将redis的配置换成自己的，可以成功运行。
> 如果按源码的配置参数，调用打分接口则会报出下述错误.
> Request processing failed; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused (Connection refused)] with root cause
> @ittqqzz 检查下redis的配置是否忘记了上传某些参数，比如端口号之类的？

README 里面说了的，所有涉及到 IP 的地方全部要改（不改，直接用我的也行），包括 business 与 recommend 模块。因为我自己不想在本地搭建中间件，所以把中间件全部上云。
但是我把阿里云 Redis 下线了，所以你会报错！可以自己搭建Redis中间价并修改IP
